### ISSUE TITLE
Collision animations

### ISSUE THREAD

**Issue by claravanstaden** [ducksboard/gridster.js#371]
My gridster instance seems to work fine, except for the fact that if you drag a widget and it overlaps with another, the slide up or slide down animation does not happen. It simply switches positions (the right position), but with no animation.

Does anyone have the same issue? Any ideas what could be causing it?

**Comment by Superdrac** [comment]
Video ? JSFiddle ? Code ?

**Comment by hrosenbauer** [comment]
You are missing the transition css properties which are in the gridster css file (line 30), e.g.

``` css
.ready .gs-w:not(.preview-holder) {
   transition: opacity .3s, left .3s, top .3s, width .3s, height .3s;
}
```
