### ISSUE TITLE
Drag drop style customization

### ISSUE THREAD

**Issue by mahitaande** [ducksboard/gridster.js#506]
Hi,
   I like how the drag drop is organised in gridster. 
I would like to know if the style for drag and drop can be customized. The style I am trying to achieve is
1. the current new widget position style is a faded area. instead can I customize it to have something with dotted border
2. When the widget is dropped, the widget flows into the new place, instead can it be customized to snap into the new place. E.g. http://datatorrent.github.io/malhar-angular-dashboard/#/

Thanks

**Comment by bondt** [comment]
Yes, you can do this very well even:
1. The element being dragged gets the class `dragging`, so feel free to play around with that. The semi-transparent 'preview' of the widget's new position is class `preview-holder`, which can be customised as well.
2. This is done by CSS3's transitions, which are in the stylesheet. Have a look at all rules with `left .3s, top .3s`, like this one:

``` CSS
.ready .gs-w:not(.preview-holder) {
    -webkit-transition: opacity .3s, left .3s, top .3s;
    -moz-transition: opacity .3s, left .3s, top .3s;
    -o-transition: opacity .3s, left .3s, top .3s;
    transition: opacity .3s, left .3s, top .3s;
}
```

When you remove `left .3s, top .3s` (without breaking the code), it'll snap in nicely.
